### PR TITLE
Fix init state + API config move to ENV file

### PR DESCRIPTION
**Pull request by Kyfi**
I know that i can use .env.local file and sensitive date will not be on repo, but if u want to start project `npm start` you will have to describe own API credentials.

### CODE REVIEW

**Review by 1kuko3 — CHANGES_REQUESTED** [review]
While moving all sensitive data to `.env` file it is good practise also to keep `config.js` file and list all entries from `.env` file here. 
All places where you will need any of environment variable will still use values from `config.js` (as you had it in first commit). For example fetch will look the same way as before, just values in `config.js` (again keys will remain the same to avoid editing all fetches) will point to particular `process.env[envVariable]`

**Comment by Kyfi** [comment]
> While moving all sensitive data to `.env` file it is good practise also to keep `config.js` file and list all entries from `.env` file here.
> All places where you will need any of environment variable will still use values from `config.js` (as you had it in first commit). For example fetch will look the same way as before, just values in `config.js` (again keys will remain the same to avoid editing all fetches) will point to particular `process.env[envVariable]`

Fixed! Thanks for notice. I will try remember this for future.

**Comment by 1kuko3** [comment]
Also the `.env` files should be listed in `.gitignore`. 
These secret information should not appear in git repository and values of environment variables can differ per environment (testing environment can be configured to have just some test products, while production environment will have real products which will be different from testing ones, and also developers can be using some another custom set of products and all this is handled just by different environment variable - it can be `apiUrl` or `cliendId` - depends on backend).
If you want to provide example values of .env file good practise for that is to create `.env.example` (with some dummy values of variables) and commit it (`.env.example` will not appear in your `.gitignore`)

**Comment by 1kuko3** [comment]
according to [CRA docs](https://facebook.github.io/create-react-app/docs/adding-custom-environment-variables#what-other-env-files-can-be-used) it should be OK just by renaming current `.env` file to `.env.development.local` (which is already included in your `.gitignore`)

**Review by 1kuko3 — CHANGES_REQUESTED** [review]
Please see comments above ^

**Comment by Kyfi** [comment]
Ok, fixed!

**Review by 1kuko3 — APPROVED** [review]

**Pull request merged**
